/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClientId = bigint;
export interface ClientSyncState {
  'url' : string,
  'position' : Cursor,
  'syncEnabled' : boolean,
}
export interface Cursor { 'x' : number, 'y' : number }
export interface _SERVICE {
  'createSession' : ActorMethod<[], string>,
  'disconnectClient' : ActorMethod<[string, ClientId], undefined>,
  'getClientCount' : ActorMethod<[string], bigint>,
  'getSessionInfo' : ActorMethod<
    [string],
    { 'masterConnected' : boolean, 'clientCount' : bigint, 'exists' : boolean }
  >,
  'getSyncState' : ActorMethod<
    [string],
    { 'clientCount' : bigint, 'master' : ClientSyncState }
  >,
  'joinSession' : ActorMethod<[string], ClientId>,
  'updateSyncState' : ActorMethod<[string, string, Cursor, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];