/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClientId = IDL.Nat;
export const Cursor = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const ClientSyncState = IDL.Record({
  'url' : IDL.Text,
  'position' : Cursor,
  'syncEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([], [IDL.Text], []),
  'disconnectClient' : IDL.Func([IDL.Text, ClientId], [], []),
  'getClientCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getSessionInfo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'masterConnected' : IDL.Bool,
          'clientCount' : IDL.Nat,
          'exists' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getSyncState' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'clientCount' : IDL.Nat, 'master' : ClientSyncState })],
      ['query'],
    ),
  'joinSession' : IDL.Func([IDL.Text], [ClientId], []),
  'updateSyncState' : IDL.Func([IDL.Text, IDL.Text, Cursor, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClientId = IDL.Nat;
  const Cursor = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const ClientSyncState = IDL.Record({
    'url' : IDL.Text,
    'position' : Cursor,
    'syncEnabled' : IDL.Bool,
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([], [IDL.Text], []),
    'disconnectClient' : IDL.Func([IDL.Text, ClientId], [], []),
    'getClientCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getSessionInfo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'masterConnected' : IDL.Bool,
            'clientCount' : IDL.Nat,
            'exists' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getSyncState' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'clientCount' : IDL.Nat, 'master' : ClientSyncState })],
        ['query'],
      ),
    'joinSession' : IDL.Func([IDL.Text], [ClientId], []),
    'updateSyncState' : IDL.Func(
        [IDL.Text, IDL.Text, Cursor, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };